### ISSUE TITLE
Obsidian Plugin

### ISSUE THREAD

**Issue by stark1tty** [KnowledgeCanvas/knowledge#105]
Hi, just here to make a request for an Obsidian and other PKM plugins. This tool is super cool. Thanks!! 🙏

**Comment by RobRoyce** [comment]
Can you elaborate a bit more on what you have in mind?

**Comment by stark1tty** [comment]
Of course, this software would be a huge boon if it is integrated into programs like Obsidian, Notion, Zettlr, OneNote and Logseq. These apps act like trapper keepers with massive libraries of often FOSS plugins which users build their own internet of things. There are huge, rapidly growing communities behind these programs especially in academia. The advantage of many these programs, other than Notion & OneNote, is that the vaults that people develop can be used interchangeably which means they will evolve and outlast programs that fail or stop development. 

Obsidian is my drug of choice so I will speak from that. It has a built in option called Canvas, which I was trying to use similarly to this app (see: https://obsidian.md/canvas). It would be massively useful for me to be able to integrate this app with Obsidian, either by being able to use it within the program or having some sort of sync option with visuals between the two. I suppose a more simple example of this is how apps like Calibre and Zotero users use Obsidian: 

https://medium.com/@alexandraphelan/an-academic-workflow-zotero-obsidian-56bf918d51ab
https://bagerbach.com/blog/how-i-read-research-papers-with-obsidian-and-zotero
https://www.reddit.com/r/ObsidianMD/comments/m5ou2h/phd_workflow_obsidian_zettelkasten_zotero_pandoc/

More of this can be found here, which can show how quite extensive and customisable these extensions get. It's very modular. 
https://www.eleanorkonik.com/resources/
https://www.eleanorkonik.com/tag/roundup/

These tools have the most staying power for me when I can integrate them with my internet of things. I know I am not alone in this. 

Here is the repo for an Obsidian plugin. There are tonnes of plugins that can be found on here as well as examples. 

https://github.com/obsidianmd/obsidian-sample-plugin

A lot of apps like yours make the mistake of trying to be an all encompassing all in one and become bloated and hard to use eventually. They become impractical because they are walled gardens. Not enough ambitious apps pick what they do and do it well and open the gates to play with others. This app has a ton of promise and I hope I can mesh it into my web as I am a visual learner. Very cool stuff going on here, thanks for what you do.

**Comment by stark1tty** [comment]
PS, sorry if I am already saying what you already know! I only have a fuzzy idea as I have just started playing with the software but it looks awesome!!

**Comment by RobRoyce** [comment]
Awesome, thank you for the feedback! I have received similar requests in the past and it is definitely something I want to look in to.

Question: do you imagine Knowledge working as a plugin for Obsidian, or would it be ingesting the data produced by your Obsidian workflow? Which features does Knowledge provide (or planning to provide) that you're not currently getting in Obsidian or some other app?

Just trying to understand better because I genuinely do care about UX and this type of feedback is important to me.

Thanks!

**Comment by stark1tty** [comment]
The most helpful plugins are when they work both ways and sync with each other. I think it may be helpful to you to see what I was trying to do with Canvas? If so I can pop it over in an email as a .pdf. I was using it to organise attachments, drafts, pdfs and websites for my phd thesis and develop some sort of flow and keep my head on straight. I also tried to do this with writing, snippets and chapter organising using mindmapping software like MindMaster.io. Knowledge seems like it would solve the problems and usability issues between the two programs. 

I already connect my notes using https://github.com/akosbalasko/zoottelkeeper-obsidian-plugin which is visualised in my obsidian graph: https://fediscience.org/system/media_attachments/files/109/833/578/676/576/042/original/9c677f752078fb33.png. It may be helpful to note that the graph file is a .json that you may be able to integrate with Knowledge as a starting point!! - https://help.obsidian.md/Plugins/Graph+view. That should probably be optional though as I store multiple projects in a vault and often just want to focus on one at a time in these things (and sometimes make sub-vaults accordingly). Others make separate vaults; it's a matter of preference. 

I guess the goal should be to enhance the experience between both apps... synergy. Something like being able to organise and automatically attach tags in a easy to use drag and drop interface, tags which could be used on both platforms would be super useful. There are apps that let you use the web within Obsidian but they are not always intuitive, but the framework is there. 

I would like to be able to use the same vault for both applications. Export to markdown is always a good option... Sidebar interfaces are useful as well as in line code. 

I hope this is helpful?

**Comment by stark1tty** [comment]
The synergy aspect is really important to me as too many steps overwhelm the ADHD brain. I use Obsidian for all of my writing too so if I have to do something manually like transferring information it is likely to be thrown on a todo pile and never get done. I think there is opportunities with a lot of Obsidian's base features.

**Comment by RobRoyce** [comment]
I don't foresee this happening unless someone else from the community decides to work on it.
