### ISSUE TITLE
My OpenAI API key is correct, but it keeps giving me errors.

### ISSUE THREAD

**Issue by DajunZhou** [KnowledgeCanvas/knowledge#128]
![image](https://github.com/KnowledgeCanvas/knowledge/assets/24242885/42ab1230-1763-4c72-9185-ee82e68ddbfe)

**Comment by RobRoyce** [comment]
Can you post additional details? For instance, try opening the developer console and looking for error messages. You might also need to run the application using a terminal window to get additional output.

I have no way of reproducing this error message, so no way of trying to "fix" it.
