### ISSUE TITLE
[Wiki] Broken link in "Basics: Sources" article

### ISSUE THREAD

**Issue by dantefromhell** [KnowledgeCanvas/knowledge#73]
While reading through the page [1] I found the text "supported digital resources" pointing to a non-existing wiki page [2]

[1] https://github.com/KnowledgeCanvas/knowledge/wiki/Basics:-Sources
[2] https://github.com/KnowledgeCanvas/knowledge/wiki/Supported-Import-Types

**Comment by RobRoyce** [comment]
Fixed. Good catch, and thanks for pointing it out! 

The "Supported Import Types" page was removed intentionally, I just forgot to remove any links pointing to it. To be revisited once the feature set is built out more.
