### ISSUE TITLE
[Bug] URLs with third level domains are considered invalid

### ISSUE THREAD

**Issue by NxDs** [KnowledgeCanvas/knowledge#87]
Attempting to add links with third level domains such as https://test.example.com will throw an invalid URL error.
This however does not happen with URLs using www such as https://www.example.com

![image](https://user-images.githubusercontent.com/7994264/219160514-5e1e13d9-bc20-41b1-9070-646478a9d000.png)

Version: 0.7.0

**Comment by ByteSyze** [comment]
Knowledge is actually handling N-level domains without issue as long as the domain is reachable. This error message could be changed to something more precise, e.g. "Website unreachable". Even better, perhaps display the HTTP response code in a debug level notification.

**Comment by BigBoyBarney** [comment]
I'll add on to this.
Some links (specifically youtube CHANNELS) cannot be added as source for some reason.

Attempting to add https://www.youtube.com/@ccmusicc (or any other channel link) will results in nothing happening.
Youtube VIDEOS on the other hand can be added without an issue. Knowledge doesn't allow us to manually edit the link target, it's impossible to add links to channels

**Comment by RobRoyce** [comment]
> I'll add on to this. Some links (specifically youtube CHANNELS) cannot be added as source for some reason. I don't even get an error toast, just straight up nothing happens haha
> 
> Attempting to add https://www.youtube.com/@ccmusicc (or any other channel link) will results in nothing happening. Youtube VIDEOS on the other hand can be added without an issue. Knowledge doesn't allow us to manually edit the link target, it's impossible to add links to channels

Interesting, this actually worked for me:

![image](https://user-images.githubusercontent.com/19367848/219506948-3fea62d7-39a0-4806-8f27-e13b54489875.png)

**Comment by RobRoyce** [comment]
> I'll add on to this. Some links (specifically youtube CHANNELS) cannot be added as source for some reason. I don't even get an error toast, just straight up nothing happens haha
> 
> Attempting to add https://www.youtube.com/@ccmusicc (or any other channel link) will results in nothing happening. Youtube VIDEOS on the other hand can be added without an issue. Knowledge doesn't allow us to manually edit the link target, it's impossible to add links to channels

Interesting, this actually worked for me:

![image](https://user-images.githubusercontent.com/19367848/219507079-39147b5c-78b2-4952-8467-895cc1d803ea.png)

**Comment by RobRoyce** [comment]
Thank you all for the analysis. I am aware of this issue but haven't had time to deep dive.

One quick solution is to alert the user when an import fails and allow you to "Import Anyways". This will likely result in a Source without icons/thumbnails/metadata, etc., but at least the link will be imported.

Another solution is to load the page in a separate window/view (which will behave differently than just using a `GET` and then have a `Confirm Import` button).

I might implement the quick solution for next release and think on a more longterm solution for later.
