### ISSUE TITLE
[Feature/Request] Option to move / import entire projects

### ISSUE THREAD

**Issue by BigBoyBarney** [KnowledgeCanvas/knowledge#88]
Hi!

I'm not sure how feasible this is or how much of a rewrite it would require, but currently only sources can be moved between projects. 

Let's say I'm planning a trip and forget to create a main "Travel" project and created 2 projects titled "Tokyo" and "Kyoto" instead, and collect websites etc I'd like to visit there. Retroactively moving these 2 projects into 1 would be super useful.

P.S.: Exporting a project as JSON (which is currently possible) and then importing it on another device would be fantastic as well (for example for sharing projects with friends etc. Incidentally, this would kind of solve the project move issue as well)

Thanks!

**Comment by RobRoyce** [comment]
Thanks for the input.

I had implemented a drag-and-drop interface for moving projects back in <= v0.5.0, but it was error prone, so I removed it.

A good solution would be either or all/any of:

1. Create a proper drag-and-drop interface
2. Add a `Move` option to the right-click menu for Projects (like with Sources)
3. Make the `Parent Project` field selectable in the `Projects > Details` pop-up 

For now, you can always create a new project and move all of the Sources to that new project. I'll see if we can get this into the next release 👍

**Comment by RobRoyce** [comment]
Added the ability to move projects (and sources) via drag-and-drop in the project tree. See 59ab8ff

**Comment by BigBoyBarney** [comment]
THAT'S MASSIVE, thank you so much!!!
