### ISSUE TITLE
[Bug] Graph sometimes displays empty node

### ISSUE THREAD

**Issue by ByteSyze** [KnowledgeCanvas/knowledge#93]
Issue: Occasionally, there will be a random gray node with no associated information displayed on the Knowledge graph.

Steps to reproduce:

1. Click on "Projects" tab
2. Click on "Graph" tab

This will spawn an empty node on the graph:
![image](https://user-images.githubusercontent.com/5094628/220527457-11b5550d-7c3a-43ea-a883-d4e0f4a576ce.png)

**Comment by RobRoyce** [comment]
I'm always surprised at the different ways in which people use `Knowledge`... you'll have to explain to me what the `bung` project is all about some day...

In the meantime, thanks for the report. There may be an extra element being added to the array of `Sources` being input into the graph component. I'll check it out (or you can open your first MR 😉 )

**Comment by RobRoyce** [comment]
This is a very strange issue. 

The stray node only appears when going from any other view to the graph view for the first time. If you switch projects while staying in the graph view, it disappears.

Further, the `id` of the element is non-deterministic (it changes every time you switch from any view to the graph view). Even more strange, the `id` I get from the node never corresponds to any existing projects or sources. But somehow the `id` is always a valid UUID...

Further research is needed.
